### ISSUE TITLE
Ask for signature after connecting with wallet

### ISSUE THREAD

**Issue by naps62** [subvisual/discoveryDAO#90]
In practical terms, instead of using the address to query the registry for a fractal ID (essentially asking if the user has made a valid KYC), we need to have to  ability to query with a signature instead

So something like `controller.kycStatusForSignature(sig)` instead (or in addition to) `controller.kycStatus(address)`

**Comment by flaviocastro** [comment]
@naps62, some UX enlightening on this:
1. Should we ask signature first and then connect or vice versa?
2. What happens if user rejects signature?
3. On change wallet, the signature must be asked again for the new address?

**Comment by naps62** [comment]
1. first connect, then signature (would it even work the other way around?)
2. I'd say the same as if they didn't connect in the first place (possibly with an error message, if we do have those?)
3. yes

**Comment by flaviocastro** [comment]
@naps62 
We will need the function on the contract in order to close this issue.
Also, any news on the message that we are signing? We will set it up as an Environment Variable for now.

**Comment by naps62** [comment]
I'll have to forward that question to @zamith for now

**Comment by flaviocastro** [comment]
@naps62 Accordingly to the "latest news", we can put anything since we are only validating the signature locally, that was only needed if we would compare signatures.
What are your toughs on this @zamith?

If no development is needed, this [issue](https://github.com/subvisual/discoveryDAO/pull/107) can close this.
